# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aeb4108dc1c112b60f87a44ca26f511a"
name = "shop-chat-agent"
handle = "shop-chat-agent"
application_url = "https://rachat.vercel.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
scopes = "read_products,read_customers"

[auth]
redirect_urls = [ "https://rachat.vercel.app/auth/callback" ]

[pos]
embedded = false

[mcp.customer_authentication]
redirect_uris = [
  "https://rachat.vercel.app/callback"
]